name: Test examples from documentation


on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - main

jobs:
  test_examples:
    runs-on: ubuntu-latest
    name: Test examples
    strategy:
      matrix:
        language: [ python, node, curl, cpp, rust ]
        include:
          - reduct_version: main
            example_root: docs/guides/examples
          - language: python
            cmd: python3
            path_prefix: py/src

          - language: node
            cmd: node
            path_prefix: js/src

          - language: curl
            path_prefix: curl
            cmd: sh

          - language: cpp
            path_prefix: cpp/build
            cmd: sh -c

          - language: rust
            path_prefix: rs/bin
            cmd: sh -c

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Run ReductStore instance
        run: |
          docker run -d --name reductstore -p 8383:8383 --env RS_API_TOKEN="my-token" reduct/store:${{ matrix.reduct_version }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.75

      - name: Install Python dependencies
        if: matrix.language == 'python'
        run: |
          pip install -r ${{ matrix.example_root }}/${{ matrix.path_prefix }}/../requirements.txt

      - name: Install Node.js dependencies
        if: matrix.language == 'node'
        run: |
          cd ${{ matrix.example_root }}/${{ matrix.path_prefix }}/..
          npm install

      - name: Build C++ examples
        if: matrix.language == 'cpp'
        run: |
          export EXAMPLE_DST_PATH="$PWD/${{ matrix.example_root }}/${{ matrix.path_prefix }}"

          git clone https://github.com/reductstore/reduct-cpp.git
          cd reduct-cpp
          cmake -DCMAKE_BUILD_TYPE=Release .
          sudo make install
          
          mkdir -p "$EXAMPLE_DST_PATH"
          cd "$EXAMPLE_DST_PATH"
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j
          # remove non-executable files from build directory
          find "$EXAMPLE_DST_PATH" -type f !  -name *.cxx | xargs rm -rf

      - name: Build Rust examples
        if: matrix.language == 'rust'
        run: |
          export EXAMPLE_DST_PATH="$PWD/${{ matrix.example_root }}/rs/build"
          mkdir -p "$EXAMPLE_DST_PATH"
          
          cargo install --examples --root . --path "$EXAMPLE_DST_PATH"/..

      - name: Run examples
        run: |
          for example in $(find ${{ matrix.example_root }}/${{ matrix.path_prefix }} -type f );
          do
            echo "Run $example"
            ${{ matrix.cmd }} "$example"
          done
          

  test_provisioning:
    runs-on: ubuntu-latest
    name: Test provisioning
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Run provisioning examples
        run: |
          for example in $(find docs/guides/examples/provisioning -type f );
          do
            docker-compose -f $example up -d
            docker-compose -f $example down
          done

